routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

/**
 * Routes Users.
 */
Route::get('/usuarios', 'UserController@index')
    ->name('users.index');

Route::get('/usuarios/{user}', 'UserController@show')
    ->where('user', '[0-9]+')
    ->name('users.show');

Route::get('/usuarios/nuevo', 'UserController@create')->name('users.create');

Route::post('/usuarios', 'UserController@store');

Route::get('/usuarios/{user}/editar', 'UserController@edit')->name('users.edit');

Route::put('/usuarios/{user}', 'UserController@update');

Route::get('/usuarios/papelera', 'UserController@trashed')->name('users.trashed');

Route::patch('/usuarios/{user}/papelera', 'UserController@trash')->name('users.trash');

Route::patch('/usuarios/{user}/restore', 'UserController@restore')->name('users.restore');

Route::delete('/usuarios/{id}', 'UserController@destroy')->name('users.destroy');

/**
 * Routes Profile.
 */
Route::get('editar-perfil/', 'ProfileController@edit');

Route::put('editar-perfil/', 'ProfileController@update');

Route::get('profesiones', 'ProfessionController@index');
Route::delete('profesiones/{profession}', 'ProfessionController@destroy');

Route::get('habilidades/', 'SkillController@index');

app/Profession.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profession extends Model
{
    //protected $table = 'my_professions';

    //public $timestamps = false;

    protected $fillable = ['title'];

    public function profiles()
    {
        return $this->hasMany(UserProfile::class);
    }
}

app/Http/Controllers/ProfessionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profession;

class ProfessionController extends Controller
{
    public function index()
    {
        $professions = Profession::query()
                        ->withCount('profiles')
                        ->orderBy('title')->get();

        return view('professions.index', [
           'professions' => $professions,
        ]);
    }

    public function destroy(Profession $profession)
    {
        abort_if($profession->profiles()->exists(), 400);

        $profession->delete();

        return redirect('profesiones');
    }
}

resources/views/professions/index.blade.php
@extends('layout')

@section('title', 'Profesiones')

@section('content')
    <div class="d-flex justify-content-between align-items-end mb-3">
        <h1 class="pb-1">Listado de profesiones</h1>
    </div>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Título</th>
            <th scope="col">Acciones</th>
        </tr>
        </thead>
        <tbody>
        @foreach($professions as $profession)
            <tr>
                <th scope="row">{{ $profession->id }}</th>
                <td>{{ $profession->title }}</td>
                <td>
                    @if ($profession->profiles_count == 0)
                    <form action="{{ url("profesiones/{$profession->id}") }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-link"><span class="oi oi-trash"></span></button>
                    </form>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

@section('sidebar')
    @parent
@endsection